all:
  children:
    cdn_master:
      hosts:
        master_node:
          ansible_host: 10.2.2.18
    cdn_webservers:
      hosts:
        web_server_node:
          ansible_host: 10.2.2.164
        web_proxy_node:
          ansible_host: 10.2.2.165
    cdn_monitoring:
      hosts:
        prometheus_node:
          ansible_host:
        grafana_node:
          ansible_host:
    cdn_containers:
      children:
        cdn_webservers:
        cdn_monitoring:
