# Ansible global settings #
#----------------------------------------#
ssh:
  private_key_location: "~/.ssh"
  private_key_name: "cdn"

ansible_host: 192.168.1.46
ansible_user: "cdn"
ansible_connection: ssh
ansible_ssh_private_key_file: "{{ ssh.private_key_location }}/{{ ssh.private_key_name }}"

## cdn_connection role variables overrides ##
#----------------------------------------#
cdn_connection_ssh: "{{ ssh }}"

## cdn_docker role variables overrides ##
#----------------------------------------#
cdn_docker_ssh: "{{ ssh }}"

cdn_docker_settings:
  user: "{{ ansible_user }}"
  password: "admin"
  image: "cdn-debian-bullseye"

cdn_docker_network_name: "cdn-network"

## cnd_nginx_browser variables overrides ##
#----------------------------------------#

## cdn_nginx_proxy variables overrides ##
#----------------------------------------#
cdn_nginx_proxy_pass_address: "{{ ansible_host }}"
cdn_nginx_proxy_pass_port: "81"
