- name: Add nginx configuration on {{ ansible_host }}:{{ nginx_port }}
  ansible.builtin.template:
    src: "nginx.proxy.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
  notify: Restart nginx

- name: Create cache folder for nginx
  ansible.builtin.file:
    path: "/var/nginx/cache"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: "0755"
