---
- name: Install nginx on webservers group
  hosts: cdn_webservers
  become: true
  tasks:
    - name: Install nginx apt package
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
