# Playbook that will install docker engine on Debian like unix distributions.
---
- name: Install Docker Engine
  hosts: cdn_master
  tasks:
    - name: Install Docker
      block:
        - name: Install apt packages
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            state: present
            update_cache: true

        - name: Add Docker’s official GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/{{ os.distribution }}/gpg
            state: present

        - name: Add Docker Repository
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/{{ os.distribution }} {{ os.version }} stable
            state: present

        - name: Update apt and install docker-ce
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: true

        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
      become: true
      become_user: root
      become_method: su

    - name: Create project folder for config
      ansible.builtin.file:
        path: "{{ project.folder }}"
        state: directory
        mode: "0755"

    - name: Add dockerfile to build image
      ansible.builtin.template:
        src: "./templates/docker/image.conf.j2"
        dest: "{{ project.folder }}/Dockerfile"
        mode: 0644

    - name: Copy public key to cdn_master_node for Dockerfile
      ansible.builtin.template:
        src: "{{ ssh.private_key_location }}{{ ssh.private_key_name }}.pub"
        dest: "{{ project.folder }}/{{ ssh.private_key_name }}.pub"
        mode: 0777
