---
# Playbook to initilized ssh conection with Ansible master node which runs
# docker containers with services. This Playbook requires "--ask-pass" for init connection without
# ssh key. This will be removed and changed in final version.

- name: Generate ssh key and config for master node
  hosts: cdn_master
  tasks:
    - name: Generate ssh key and config on localhost
      block:
        - name: Generate ssh key on localhost for master node
          community.crypto.openssh_keypair:
            path: "{{ ssh.private_key_location }}{{ ssh.private_key_name }}"
            type: rsa
            size: 4096
            state: present
            force: no

        - name: Get remote host key from nodes
          ansible.builtin.shell:
            cmd: ssh-keyscan {{ hostvars.master_node.ansible_host }}
          register: ssh_known_host_results
          ignore_errors: yes

        - name: Debug
          debug:
            var: ssh_known_host_results

        - name: Add remote host key to known_hosts
          ansible.builtin.known_hosts:
            name: "{{ hostvars.master_node.ansible_host }}"
            path: ~/.ssh/known_hosts
            key: "{{ ssh_known_host_results.stdout }}"
            state: present

        ## Destination is directory in ~/.ssh/cdn.d/ which is included in .ssh/config

        - name: Create a ssh config file
          ansible.builtin.template:
            src: "./templates/ssh/ssh.conf.j2"
            dest: "{{ ssh.private_key_location }}cdn.d/{{ hostvars.master_node.inventory_hostname }}"
            mode: 0644
          loop: "{{ groups.cdn_master }}"
      delegate_to: localhost

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '{{ ssh.private_key_location }}{{ ssh.private_key_name }}.pub') }}"
