- name: Generate ssh key and config on localhost
  block:
    - name: Generate ssh key on localhost for master node
      community.crypto.openssh_keypair:
        path: "{{ cdn_connection_ssh.private_key_location }}/{{ cdn_connection_ssh.private_key_name }}"
        type: rsa
        size: 4096
        state: present
        force: no

    - name: Create project folder for inventory configs
      ansible.builtin.file:
        path: "~/.ssh/{{ cdn_connection_ssh.private_key_name}}.d"
        state: directory
        mode: "0755"
      register: ssh_project_file

    - name: Create a ssh config file
      ansible.builtin.template:
        src: "ssh.conf.j2"
        dest: "{{ ssh_project_file.path }}/{{ inventory_hostname }}"
        mode: "0644"

    - name: Create a include line in ssh config
      ansible.builtin.lineinfile:
        path: "~/.ssh/config"
        insertbefore: BOF
        line: "Include {{ ssh_project_file.path }}/*"
  delegate_to: localhost
