- name: Create a network with custom IPAM config and network driver
  community.docker.docker_network:
    name: "{{ cdn_docker_network_name }}"
    driver: "{{ cdn_docker_network_driver }}"
    driver_options:
      parent: "{{ cdn_docker_network_settings.interface }}"
    ipam_config:
      - subnet: "{{ cdn_docker_network_settings.subnet }}"
        gateway: "{{ cdn_docker_network_settings.gateway }}"
  become: true
  become_method: su

- name: Build image with Debian OS
  community.docker.docker_image:
    build:
      path: "{{ cdn_docker_project }}"
    name: "{{ cdn_docker_settings.image }}"
    source: build

- name: Start containers
  community.docker.docker_container:
    name: "{{ item }}"
    image: "{{ cdn_docker_settings.image }}"
    cgroup_parent: docker.slice
    cgroupns_mode: private
    capabilities:
      - SYS_ADMIN
    interactive: true
    privileged: true
    networks:
      - name: "{{ cdn_docker_network_name }}"
        ipv4_address: "{{ hostvars[item].ansible_host }}"
    mounts:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
  loop: "{{ groups[cdn_docker_hosts] }}"
