- name: Get remote host key from nodes
  ansible.builtin.shell:
    cmd: ssh-keyscan {{ hostvars[item].ansible_host }}
  register: ssh_known_host_results
  ignore_errors: yes
  loop: "{{ groups[cdn_docker_hosts.group] }}"

- name: Debug
  ansible.builtin.debug:
    var: ssh_known_host_results

- name: Add remote host key to known_hosts
  ansible.builtin.known_hosts:
    name: "{{ hostvars[item.item].ansible_host }}"
    path: ~/.ssh/known_hosts
    key: "{{ item.stdout }}"
    state: present
  loop: "{{ ssh_known_host_results.results }}"
